/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as TeamStudentsRouteImport } from './routes/team/students'
import { Route as TeamResearchersRouteImport } from './routes/team/researchers'
import { Route as TeamFacultyRouteImport } from './routes/team/faculty'
import { Route as ProjectsAuscultationTrainingErLabRouteImport } from './routes/projects/auscultation-trainingEr-lab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamStudentsRoute = TeamStudentsRouteImport.update({
  id: '/team/students',
  path: '/team/students',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamResearchersRoute = TeamResearchersRouteImport.update({
  id: '/team/researchers',
  path: '/team/researchers',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamFacultyRoute = TeamFacultyRouteImport.update({
  id: '/team/faculty',
  path: '/team/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsAuscultationTrainingErLabRoute =
  ProjectsAuscultationTrainingErLabRouteImport.update({
    id: '/projects/auscultation-trainingEr-lab',
    path: '/projects/auscultation-trainingEr-lab',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/auscultation-trainingEr-lab': typeof ProjectsAuscultationTrainingErLabRoute
  '/team/faculty': typeof TeamFacultyRoute
  '/team/researchers': typeof TeamResearchersRoute
  '/team/students': typeof TeamStudentsRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/auscultation-trainingEr-lab': typeof ProjectsAuscultationTrainingErLabRoute
  '/team/faculty': typeof TeamFacultyRoute
  '/team/researchers': typeof TeamResearchersRoute
  '/team/students': typeof TeamStudentsRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/auscultation-trainingEr-lab': typeof ProjectsAuscultationTrainingErLabRoute
  '/team/faculty': typeof TeamFacultyRoute
  '/team/researchers': typeof TeamResearchersRoute
  '/team/students': typeof TeamStudentsRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/auscultation-trainingEr-lab'
    | '/team/faculty'
    | '/team/researchers'
    | '/team/students'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/auscultation-trainingEr-lab'
    | '/team/faculty'
    | '/team/researchers'
    | '/team/students'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/projects/auscultation-trainingEr-lab'
    | '/team/faculty'
    | '/team/researchers'
    | '/team/students'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsAuscultationTrainingErLabRoute: typeof ProjectsAuscultationTrainingErLabRoute
  TeamFacultyRoute: typeof TeamFacultyRoute
  TeamResearchersRoute: typeof TeamResearchersRoute
  TeamStudentsRoute: typeof TeamStudentsRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/students': {
      id: '/team/students'
      path: '/team/students'
      fullPath: '/team/students'
      preLoaderRoute: typeof TeamStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/researchers': {
      id: '/team/researchers'
      path: '/team/researchers'
      fullPath: '/team/researchers'
      preLoaderRoute: typeof TeamResearchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/faculty': {
      id: '/team/faculty'
      path: '/team/faculty'
      fullPath: '/team/faculty'
      preLoaderRoute: typeof TeamFacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/auscultation-trainingEr-lab': {
      id: '/projects/auscultation-trainingEr-lab'
      path: '/projects/auscultation-trainingEr-lab'
      fullPath: '/projects/auscultation-trainingEr-lab'
      preLoaderRoute: typeof ProjectsAuscultationTrainingErLabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsAuscultationTrainingErLabRoute:
    ProjectsAuscultationTrainingErLabRoute,
  TeamFacultyRoute: TeamFacultyRoute,
  TeamResearchersRoute: TeamResearchersRoute,
  TeamStudentsRoute: TeamStudentsRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
