/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsAuscultationTrainingErLabRouteImport } from './routes/projects/auscultation-trainingEr-lab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsAuscultationTrainingErLabRoute =
  ProjectsAuscultationTrainingErLabRouteImport.update({
    id: '/projects/auscultation-trainingEr-lab',
    path: '/projects/auscultation-trainingEr-lab',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/auscultation-trainingEr-lab': typeof ProjectsAuscultationTrainingErLabRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/auscultation-trainingEr-lab': typeof ProjectsAuscultationTrainingErLabRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/auscultation-trainingEr-lab': typeof ProjectsAuscultationTrainingErLabRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects/auscultation-trainingEr-lab' | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/auscultation-trainingEr-lab' | '/projects'
  id: '__root__' | '/' | '/projects/auscultation-trainingEr-lab' | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsAuscultationTrainingErLabRoute: typeof ProjectsAuscultationTrainingErLabRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/auscultation-trainingEr-lab': {
      id: '/projects/auscultation-trainingEr-lab'
      path: '/projects/auscultation-trainingEr-lab'
      fullPath: '/projects/auscultation-trainingEr-lab'
      preLoaderRoute: typeof ProjectsAuscultationTrainingErLabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsAuscultationTrainingErLabRoute:
    ProjectsAuscultationTrainingErLabRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
